In [3]:
import pandas as pd
csv_df = pd.read_csv('cars.csv', delimiter=";")

csv_df.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US

In [7]:
import numpy as np
#1. create an array with three dimensions
a = np.array([[[1,2,3]]])
a.ndim
a

array([[[1, 2, 3]]])

In [11]:
#2 create a 6 dimension array
b = np.array([[[1,2,3]]], ndmin=6)
b.ndim
b

array([[[[[[1, 2, 3]]]]]])

In [12]:
# 3. 
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
b = np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
b = b.T
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [24]:
b = b.transpose((1,0))
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [30]:
c = np.sqrt(b)
c

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])

In [29]:
bool_index = c >1.5
bool_index

array([[False, False,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [31]:
c[bool_index]

array([2.        , 2.44948974, 2.82842712, 1.73205081, 2.23606798,
       2.64575131, 3.        ])