In [2]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [4]:
#1 
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
b.ndim
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [6]:
#2 
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]], ndmin=6)
c

array([[[[[[1, 2, 3],
           [4, 5, 6]],

          [[1, 2, 3],
           [4, 5, 6]]]]]])

In [7]:
# 3

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [21]:
b = np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
b = b.T
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [26]:
b = b.transpose((1,0))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
np.sqrt(b)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])