In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [3]:
print(a.ndim)

2


In [4]:
print(a.shape)

(2, 3)


In [5]:
a.dtype

dtype('float32')

In [8]:
#array exercise
#1 
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
b.ndim

3

In [9]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a = np.arange(10).reshape(5,2) 
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
a = a.T 
a


array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [15]:
a = a.transpose((1,0)) 
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
np.sqrt(a)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])